/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/oauth2/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Creates an account with session in the db, and returns user object. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["def-0"]["LoadUserInputSchema"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["def-0"]["UserSchema"];
                    };
                };
            };
        };
        /** @description Logs out session assosiated with the bearer */
        delete: {
            parameters: {
                query?: never;
                header: {
                    authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Succesfully logged out from the account */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routine/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetches given user tasks */
        get: {
            parameters: {
                query?: never;
                header: {
                    authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["def-1"]["FetchTasksResponseSchema"];
                    };
                };
            };
        };
        /** @description Updates the data of the daily tasks */
        put: {
            parameters: {
                query?: never;
                header: {
                    authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["def-1"]["UpdateTasksInputSchema"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["def-1"]["UpdateTasksResponseSchema"];
                    };
                };
            };
        };
        /** @description Create new daily task */
        post: {
            parameters: {
                query?: never;
                header: {
                    authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["def-1"]["CreateTaskInputSchema"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["def-1"]["TaskSchema"];
                    };
                };
            };
        };
        /** @description Deletes daily task */
        delete: {
            parameters: {
                query?: never;
                header: {
                    authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["def-1"]["DeleteTaskInputSchema"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tag/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch all tags from the user */
        get: {
            parameters: {
                query?: never;
                header: {
                    authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["def-2"]["FetchTagsResponseSchema"];
                    };
                };
            };
        };
        put?: never;
        /** @description Create new tag */
        post: {
            parameters: {
                query?: never;
                header: {
                    authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["def-2"]["CreateTagInputSchema"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["def-2"]["TagSchema"];
                    };
                };
            };
        };
        /** @description Delete tag */
        delete: {
            parameters: {
                query?: never;
                header: {
                    authorization: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["def-2"]["DeleteTagInputSchema"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** UsersSchema */
        "def-0": {
            UserSchema: {
                id: string;
                name: string;
                email: string;
                picture: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                lastSeenAt: string;
                timeZone: string;
            };
            CreateUserInputSchema: {
                token: string;
                timeZone: string;
            };
            GoogleAccountSchema: {
                id: string;
                /** Format: email */
                email: string;
                name: string;
                picture: string;
                timeZone: string;
            };
            HeaderBearerSchema: {
                authorization: string;
            };
            LoadUserInputSchema: {
                token: string;
                timeZone?: string;
            };
        };
        /** TaskSchemas */
        "def-1": {
            TaskSchema: {
                id: string;
                position: number;
                /** @enum {string} */
                taskType: "ROUTINE" | "TODOLIST";
                priority: ("LOW" | "MEDIUM" | "HIGH" | "CRITICAL" | "OPTIONAL") | null;
                title: string;
                content: number | string | boolean | null | unknown[] | {
                    [key: string]: unknown;
                };
                /** @default false */
                isCompleted: boolean;
                /**
                 * Format: date-time
                 * @default {}
                 */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
                deadline: string | null;
                userId: components["schemas"]["def-1"]["TaskSchema"]["id"] | null;
                tagIds: components["schemas"]["def-1"]["TaskSchema"]["id"][];
            };
            CreateTaskInputSchema: {
                title: components["schemas"]["def-1"]["TaskSchema"]["title"];
                taskType: components["schemas"]["def-1"]["TaskSchema"]["taskType"];
            };
            FetchTasksResponseSchema: components["schemas"]["def-1"]["TaskSchema"][];
            DeleteTaskInputSchema: {
                id: components["schemas"]["def-1"]["TaskSchema"]["id"];
            };
            UpdateTasksInputSchema: {
                id: components["schemas"]["def-1"]["TaskSchema"]["id"];
                position: components["schemas"]["def-1"]["TaskSchema"]["position"];
                taskType: components["schemas"]["def-1"]["TaskSchema"]["taskType"];
                priority: components["schemas"]["def-1"]["TaskSchema"]["priority"];
                title: components["schemas"]["def-1"]["TaskSchema"]["title"];
                content: components["schemas"]["def-1"]["TaskSchema"]["content"];
                isCompleted?: components["schemas"]["def-1"]["TaskSchema"]["isCompleted"];
                deadline: components["schemas"]["def-1"]["TaskSchema"]["deadline"];
                tagIds: components["schemas"]["def-1"]["TaskSchema"]["tagIds"];
            }[];
            UpdateTasksResponseSchema: components["schemas"]["def-1"]["TaskSchema"][];
        };
        /** TagSchemas */
        "def-2": {
            TagSchema: {
                id: string;
                name: string;
                color: string;
                userId: components["schemas"]["def-2"]["TagSchema"]["id"] | null;
                taskIds: components["schemas"]["def-2"]["TagSchema"]["id"][];
            };
            CreateTagInputSchema: {
                name: components["schemas"]["def-2"]["TagSchema"]["name"];
                color: components["schemas"]["def-2"]["TagSchema"]["color"];
            };
            DeleteTagInputSchema: {
                id: components["schemas"]["def-2"]["TagSchema"]["id"];
            };
            FetchTagsResponseSchema: components["schemas"]["def-2"]["TagSchema"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
