/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import type {EditorThemeClasses} from 'lexical';

import './daylytic-theme.css';

export const theme: EditorThemeClasses = {
  autocomplete: 'DaylyticTheme__autocomplete',
  blockCursor: 'DaylyticTheme__blockCursor',
  characterLimit: 'DaylyticTheme__characterLimit',
  code: 'DaylyticTheme__code ant-typography',
  codeHighlight: {
    atrule: 'DaylyticTheme__tokenAttr',
    attr: 'DaylyticTheme__tokenAttr',
    boolean: 'DaylyticTheme__tokenProperty',
    builtin: 'DaylyticTheme__tokenSelector',
    cdata: 'DaylyticTheme__tokenComment',
    char: 'DaylyticTheme__tokenSelector',
    class: 'DaylyticTheme__tokenFunction',
    'class-name': 'DaylyticTheme__tokenFunction',
    comment: 'DaylyticTheme__tokenComment',
    constant: 'DaylyticTheme__tokenProperty',
    deleted: 'DaylyticTheme__tokenProperty',
    doctype: 'DaylyticTheme__tokenComment',
    entity: 'DaylyticTheme__tokenOperator',
    function: 'DaylyticTheme__tokenFunction',
    important: 'DaylyticTheme__tokenVariable',
    inserted: 'DaylyticTheme__tokenSelector',
    keyword: 'DaylyticTheme__tokenAttr',
    namespace: 'DaylyticTheme__tokenVariable',
    number: 'DaylyticTheme__tokenProperty',
    operator: 'DaylyticTheme__tokenOperator',
    prolog: 'DaylyticTheme__tokenComment',
    property: 'DaylyticTheme__tokenProperty',
    punctuation: 'DaylyticTheme__tokenPunctuation',
    regex: 'DaylyticTheme__tokenVariable',
    selector: 'DaylyticTheme__tokenSelector',
    string: 'DaylyticTheme__tokenSelector',
    symbol: 'DaylyticTheme__tokenProperty',
    tag: 'DaylyticTheme__tokenProperty',
    url: 'DaylyticTheme__tokenOperator',
    variable: 'DaylyticTheme__tokenVariable',
  },
  embedBlock: {
    base: 'DaylyticTheme__embedBlock',
    focus: 'DaylyticTheme__embedBlockFocus',
  },
  hashtag: 'DaylyticTheme__hashtag',
  heading: {
    h1: 'ant-typography',
    h2: 'ant-typography',
    h3: 'ant-typography',
    h4: 'ant-typography',
    h5: 'ant-typography',
    h6: 'ant-typography',
  },
  hr: 'DaylyticTheme__hr',
  image: 'editor-image',
  indent: 'DaylyticTheme__indent',
  inlineImage: 'inline-editor-image',
  layoutContainer: 'DaylyticTheme__layoutContainer',
  layoutItem: 'DaylyticTheme__layoutItem',
  link: 'DaylyticTheme__link',
  list: {
    checklist: 'DaylyticTheme__checklist',
    listitem: 'DaylyticTheme__listItem',
    listitemChecked: 'DaylyticTheme__listItemChecked',
    listitemUnchecked: 'DaylyticTheme__listItemUnchecked',
    nested: {
      listitem: 'DaylyticTheme__nestedListItem',
    },
    olDepth: [
      'DaylyticTheme__ol1',
      'DaylyticTheme__ol2',
      'DaylyticTheme__ol3',
      'DaylyticTheme__ol4',
      'DaylyticTheme__ol5',
    ],
    ul: 'DaylyticTheme__ul',
  },
  ltr: 'DaylyticTheme__ltr',
  mark: 'DaylyticTheme__mark',
  markOverlap: 'DaylyticTheme__markOverlap',
  paragraph: 'ant-typography',
  quote: 'DaylyticTheme__quote',
  rtl: 'DaylyticTheme__rtl',
  specialText: 'DaylyticTheme__specialText',
  tab: 'DaylyticTheme__tabNode',
  table: 'DaylyticTheme__table',
  tableAlignment: {
    center: 'DaylyticTheme__tableAlignmentCenter',
    right: 'DaylyticTheme__tableAlignmentRight',
  },
  tableCell: 'DaylyticTheme__tableCell',
  tableCellActionButton: 'DaylyticTheme__tableCellActionButton',
  tableCellActionButtonContainer:
    'DaylyticTheme__tableCellActionButtonContainer',
  tableCellHeader: 'DaylyticTheme__tableCellHeader',
  tableCellResizer: 'DaylyticTheme__tableCellResizer',
  tableCellSelected: 'DaylyticTheme__tableCellSelected',
  tableRowStriping: 'DaylyticTheme__tableRowStriping',
  tableScrollableWrapper: 'DaylyticTheme__tableScrollableWrapper',
  tableSelected: 'DaylyticTheme__tableSelected',
  tableSelection: 'DaylyticTheme__tableSelection',
  text: {
    bold: 'DaylyticTheme__textBold',
    capitalize: 'DaylyticTheme__textCapitalize',
    code: 'DaylyticTheme__textCode',
    italic: 'DaylyticTheme__textItalic',
    lowercase: 'DaylyticTheme__textLowercase',
    strikethrough: 'DaylyticTheme__textStrikethrough',
    subscript: 'DaylyticTheme__textSubscript',
    superscript: 'DaylyticTheme__textSuperscript',
    underline: 'DaylyticTheme__textUnderline',
    underlineStrikethrough: 'DaylyticTheme__textUnderlineStrikethrough',
    uppercase: 'DaylyticTheme__textUppercase',
  },
};