// USER

// GOALS
const MAX_GOAL_TITLE_LENGTH = 32;
const MIN_GOAL_TITLE_LENGTH = 4;

const MAX_GOAL_DESCRIPTION_LENGTH = 90;
const MIN_GOAL_DESCRIPTION_LENGTH = 0;

//TODO

export const goals = {
    MAX_GOAL_TITLE_LENGTH,
    MIN_GOAL_TITLE_LENGTH,
    MAX_GOAL_DESCRIPTION_LENGTH,
    MIN_GOAL_DESCRIPTION_LENGTH
}