// GOALS
export const GOAL_TITLE_MAX_LENGTH = 100;
export const GOAL_TITLE_MIN_LENGTH = 4;

export const GOAL_DESCRIPTION_MAX_LENGTH = 1000;
export const GOAL_DESCRIPTION_MIN_LENGTH = 0;

//TASK
export const TASK_TITLE_MIN_LENGTH = 1;
export const TASK_TITLE_MAX_LENGTH = 100;

//PROJECT
export const PROJECT_TITLE_MIN_LENGTH = 1;
export const PROJECT_TITLE_MAX_LENGTH = 100;

